### ISSUE TITLE
Parse authors.yml to POJO and bring back database functionality

### ISSUE THREAD

**Issue by shsanayei** [adessoAG/jekyll2cms#46]
## Tasks for this issue:
- [x] Find a way to parse authors.yml to Author object (POJO)
- [x] Integrate parsing of authors.yml into the blog creating process
- [x] Create database model including an author table
